name: we_pei_yang_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# 请保证 'package:we_pei_yang_flutter/commons/environment/config.dart'
# 中的 version 和 versionCode 保持一致
version: 4.3.16+130

# 打包代码 flutter build apk --split-per-abi
# flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

environment:
  # sdk: ">=2.10.0 <3.0.0"
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.8.2
  amap_location_fluttify: ^0.22.0

  badges: ^3.1.1

  connectivity_plus: ^2.3.7
  cached_network_image: ^3.2.3
  card_swiper: ^2.0.1

  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  dio_cookie_caching_handler:
    path: ./lib/commons/network/dio_cookie_cached_handler

  extended_tabs: ^4.1.0
  extended_image: ^8.0.1

  flutter_displaymode: ^0.6.0
  flutter_html: ^2.0.0
  flutter_markdown: ^0.6.9+1
  flutter_rating_bar: ^4.0.0
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.7.0
  flutter_smart_dialog: ^3.3.5
  flutter_svg: ^0.22.0

  fluttertoast: ^8.0.8

  gallery_saver: ^2.3.2

  http_parser: ^4.0.0

  image_cropper: ^1.5.0
  image_picker: ^0.8.4+1
  intl: ^0.18.0

  like_button: ^2.0.3
  linkfy_text: ^1.1.5

  mutex: ^3.0.0

  optimized_cached_image: ^3.0.1

  path_provider: ^2.0.4
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0

  retry: ^3.1.0

  screenshot: ^1.2.3 # 还没用到
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.7
  simple_html_css: ^3.0.1
  simple_url_preview_v2: ^4.0.2
  flutter_link_previewer: ^3.2.1

  table_calendar: ^3.0.7

  url_launcher: ^6.1.5
  uuid: ^3.0.6

  webview_flutter: ^2.0.13
  wechat_assets_picker: ^8.5.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/calender/
    - assets/images/account/
    - assets/images/account/1.5x/
    - assets/images/account/2.0x/
    - assets/images/account/3.0x/
    - assets/images/account/4.0x/
    - assets/images/schedule/
    - assets/images/studyroom_icons/
    - assets/images/lake_butt_icons/
    - assets/svg_pics/
    - assets/svg_pics/lake_butt_icons/
    - privacy/

  fonts:
    - family: Fourche
      fonts:
        - asset: assets/fonts/en/SFFourcheBoldItalic.ttf
          style: italic

    - family: Swis
      fonts:
        - asset: assets/fonts/en/Swis721-Blk-BT-Black-2.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/en/ProductSans-Bold.ttf
        - asset: assets/fonts/en/ProductSans-Regular.ttf

#    - family: NotoSansSC
#      fonts:
#        - asset: assets/fonts/zh/NotoSansSC-Medium.otf
#
#    - family: PingFangSC
#      fonts:
#        - asset: assets/fonts/zh/PingFangSC-SemiBold.ttf

flutter_intl:
  enabled: true
