name: we_pei_yang_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# 请保证 'package:we_pei_yang_flutter/commons/environment/config.dart'
# 中的 version 和 versionCode 保持一致
version: 4.4.7+148

# Build:
# flutter build apk \
#  --dart-define=ENVIRONMENT=RELEASE \
#  --dart-define=VERSION=4.4.7 \
#  --dart-define=VERSIONCODE=148 \
#  --target-platform=android-arm,android-arm64 \
#  --split-per-abi \
#  --obfuscate --split-debug-info=HLQ_Struggle

environment:
  # sdk: ">=2.10.0 <3.0.0"
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.8.2
  #  amap_location_fluttify: ^0.22.0

  pointycastle: ^3.1.1
  xml: ^6.5.0
  # 显示二维码
  syncfusion_flutter_barcodes: ^25.1.42

  badges: ^3.1.1

  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  card_swiper: ^3.0.1

  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  dio_cookie_caching_handler:
    path: ./lib/commons/network/dio_cookie_cached_handler

  extended_tabs: ^4.1.0
  extended_image: any

  flutter_displaymode: ^0.6.0
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html.git
      ref: 79ec194fa6690e5caba58f5eca04e6748394bb6b
  flutter_markdown: ^0.6.22
  flutter_rating_bar: ^4.0.1
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.9.0
  flutter_smart_dialog: ^4.9.8+2
  flutter_svg: ^2.0.10

  fluttertoast: ^8.2.4

  gallery_saver:
    git:
      url: https://github.com/steven12138/gallery_saver_deps.git


  http_parser: ^4.0.2
  glass_kit: any
  frosted_glass_effect: any

  image_cropper: ^1.5.0
  image_picker: ^1.0.7

  like_button: ^2.0.5
  linkfy_text:
    git:
      url: https://github.com/Iamstanlee/linkfy_text.git

  mutex: ^3.1.0

  #  optimized_cached_image: ^3.0.1

  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0

  retry: ^3.1.2
  flutter_reorderable_grid_view: ^4.0.0

  screenshot: ^2.1.0 # generate comment image
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  simple_html_css: ^4.0.0
  simple_url_preview_v2:
    git:
      url: https://github.com/steven12138/flutter-simple-url-preview_deps.git
  flutter_link_previewer: ^3.2.2

  table_calendar: ^3.0.9

  url_launcher: ^6.2.5
  uuid: ^4.3.3

  webview_flutter: ^2.0.13 # TODO: update the new webview package
  wechat_assets_picker: any
  window_manager: ^0.3.8

  waterfall_flow: ^3.0.3

  image_size_getter: ^2.1.2
  #  image_size_getter_http_input: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0

  # 用于图片加载占位符
  transparent_image: ^2.0.1

  package_info_plus: ^6.0.0
  glass: any
#  device_info_plus: ^9.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/calender/
    - assets/images/account/
    - assets/images/account/1.5x/
    - assets/images/account/2.0x/
    - assets/images/account/3.0x/
    - assets/images/account/4.0x/
    - assets/images/schedule/
    - assets/images/studyroom_icons/
    - assets/images/lake_butt_icons/
    - assets/images/lost_and_found_icons/
    - assets/svg_pics/
    - assets/svg_pics/lake_butt_icons/
    - assets/svg_pics/laf_butt_icons/
    - privacy/

  fonts:
    - family: Fourche
      fonts:
        - asset: assets/fonts/en/SFFourcheBoldItalic.ttf
          style: italic

    - family: Swis
      fonts:
        - asset: assets/fonts/en/Swis721-Blk-BT-Black-2.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/en/ProductSans-Bold.ttf
        - asset: assets/fonts/en/ProductSans-Regular.ttf

#    - family: NotoSansSC
#      fonts:
#        - asset: assets/fonts/zh/NotoSansSC-Medium.otf
#
#    - family: PingFangSC
#      fonts:
#        - asset: assets/fonts/zh/PingFangSC-SemiBold.ttf

